### ISSUE TITLE
Отсутствует возможность удалить узел из кластера так, что бы распределение узлов по хостам не нарушилось

### ISSUE THREAD

**Issue by Kasen** [picodata/genin#105]
Таким образом я не могу сделать expel какому-то инстансу в кластере.

**Comment by VifleY** [comment]
Если я удалю узел из конфига генина, то `genin` при перегенерации на его место распределит другой инстанс, что приведет к несоответствию старого и нового `ansible-inventory`. 
Чтобы этого избежать `genin` должен каким-либо образом хранить информацию о текущем состоянии кластера (возможно, необходима также возможность генерить ее из ansible-inventory), и учитывать ее при распределении узлов.

Что нужно учитывать:
1) Нельзя перемещать узлы существующего кластера на новые места
(не смог сходу придумать другие, но, наверняка, я упускаю что-то)

Скорее всего, хранить стоит в каком-то сериализованном формате, например, в yaml файле `genin.state`
