### ISSUE TITLE
Генин разделяет состояние между двумя разными кластерами, если файлы для них в одной папке

### ISSUE THREAD

**Issue by aensidhe** [picodata/genin#165]
### Дано

```yml
hosts:
   cluster.A.genin.yml
   cluster.B.genin.yml
```

В кластерах А и B есть репликасеты и хосты с одинаковыми именами, но на самом деле это два независимых кластера (не пересекаются по серверам, куда идёт разливка)

Выполняем:

```bash
genin build -s cluster.A.genin.yml -o inventory.A.yml -f --fd-as-zone
genin build -s cluster.B.genin.yml -o inventory.B.yml -f --fd-as-zone
```

### Что ожидается

Сгенерированы два полностью независимых инвентаря, соответствующие входным файлам.

### Что происходит

В результате в `inventory.B.yml` будут переиспользованы хосты из кластера А, что приведёт к неверной раскатке. 

### Как обойти

Удаление папки `.geninstate` между первым и вторым вызовом помогает.

### Предложение

Добавить параметр `--state-name`, который принимает произвольную строку на вход. По умолчанию равен значению параметра `-s`. При сохранении состояния сохранять имя состояния. Переиспользовать то и только то состояние, имя которого равно текущему.

**Comment by alrsorokin** [comment]
Вы можете разделить директории для хранения стейта, для этого воспользуйтесь ключом `--state-dir`
на ваших примерах:
```sh
genin build -s cluster.A.genin.yml -o inventory.A.yml -f --fd-as-zone --state-dir .geninstate_a
genin build -s cluster.A.genin.yml -o inventory.A.yml -f --fd-as-zone --state-dir .geninstate_b
```
